# ruff: noqa
"""Add ledger accounts

Revision ID: 62d9d53e1126
Revises: 202607010015
Create Date: 2026-08-02 13:18:53.010809+00:00
"""

from alembic import op
import sqlalchemy as sa


revision = '62d9d53e1126'
down_revision = '202607010015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Compatibility marker. This autogenerated migration rewrites constraints
    # that do not exist on a fresh SQLite schema; ledger accounts are created
    # by the application service instead.
    return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_addresses_customer_id'))

    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_customer_id'))

    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tags_customer_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_company_id_status'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_company_status'))

    with op.batch_alter_table('external_resource_map', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_external_resource_map_external'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_external_resource_map_company_id'), ['company_id', 'connector', 'external_resource_type', 'external_resource_id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_journal_entries_company_status'))

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_entry_id'))

    with op.batch_alter_table('marketplace_commission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_commission_rules_company_vendor'))

    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_delivery_logs_notification_id'))

    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_queue_company_channel_status'))

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_company_channel'))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_company_vendor'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_product'))

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_company_id_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_company_id_status'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    with op.batch_alter_table('product_category_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_links_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_category_links_product_id'))

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))
        batch_op.drop_constraint(batch_op.f('uq_product_images_company_product_external'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_product_images_company_id'), ['company_id', 'product_id', 'external_id'])

    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_relationships_source_product_id'))

    with op.batch_alter_table('product_tag_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tag_links_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_tag_links_tag_id'))

    with op.batch_alter_table('product_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tags_company_id'))

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_company_id_status'))
        batch_op.drop_index(batch_op.f('ix_products_company_vendor'))
        batch_op.drop_constraint(batch_op.f('uq_products_company_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_products_company_id'), ['company_id', 'sku'])

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_product'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_stock_lookup'))

    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_status'))

    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_outbox_status_next_attempt_at'))

    with op.batch_alter_table('sync_run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_run_logs_company_connector_started_at'))
        batch_op.drop_index(batch_op.f('ix_sync_run_logs_connector_started_at'))

    with op.batch_alter_table('vendor_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_ledger_entries_company_vendor'))

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_notifications_company_vendor_status'))

    with op.batch_alter_table('vendor_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_order_items_company_vendor_created_at'))

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_products_company_vendor_status'))

    with op.batch_alter_table('vendor_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_settlements_company_vendor_status'))

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_users_vendor_id'))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_company_status'))

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_company_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_company_status'), ['company_id', 'status'], unique=False)

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_users_vendor_id'), ['vendor_id'], unique=False)

    with op.batch_alter_table('vendor_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_settlements_company_vendor_status'), ['company_id', 'vendor_id', 'status'], unique=False)

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_products_company_vendor_status'), ['company_id', 'vendor_id', 'approval_status'], unique=False)

    with op.batch_alter_table('vendor_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_order_items_company_vendor_created_at'), ['company_id', 'vendor_id', 'created_at'], unique=False)

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_notifications_company_vendor_status'), ['company_id', 'vendor_id', 'status'], unique=False)

    with op.batch_alter_table('vendor_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_ledger_entries_company_vendor'), ['company_id', 'vendor_id'], unique=False)

    with op.batch_alter_table('sync_run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_run_logs_connector_started_at'), ['connector', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_logs_company_connector_started_at'), ['company_id', 'connector', 'started_at'], unique=False)

    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_outbox_status_next_attempt_at'), ['status', 'next_attempt_at'], unique=False)

    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_conflicts_status'), ['status'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_stock_lookup'), ['company_id', 'warehouse_id', 'product_id', 'variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference'), ['company_id', 'reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product'), ['company_id', 'product_id', 'variant_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_company_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_products_company_id'), ['company_id', 'slug'])
        batch_op.create_index(batch_op.f('ix_products_company_vendor'), ['company_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_company_id_status'), ['company_id', 'status'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('product_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tags_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('product_tag_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tag_links_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_tag_links_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_relationships_source_product_id'), ['source_product_id'], unique=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_images_company_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_product_images_company_product_external'), ['company_id', 'product_id', 'external_id'])
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('product_category_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_links_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_links_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_company_id_status'), ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_company_id_customer_id'), ['company_id', 'customer_id'], unique=False)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id', 'created_at'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_product'), ['company_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_company_vendor'), ['company_id', 'vendor_id'], unique=False)

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_company_channel'), ['company_id', 'channel'], unique=False)

    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_queue_company_channel_status'), ['company_id', 'channel', 'status'], unique=False)

    with op.batch_alter_table('notification_delivery_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_delivery_logs_notification_id'), ['notification_id'], unique=False)

    with op.batch_alter_table('marketplace_commission_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_commission_rules_company_vendor'), ['company_id', 'vendor_id'], unique=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_company_status'), ['company_id', 'status'], unique=False)
        batch_op.alter_column('source_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('external_resource_map', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_external_resource_map_company_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_external_resource_map_external'), ['company_id', 'connector', 'external_resource_type', 'external_resource_id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_company_status'), ['company_id', 'status'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_company_id_status'), ['company_id', 'status'], unique=False)

    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tags_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_notes_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_addresses_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###
